# Generated by Django 4.2.5 on 2023-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='upload',
            field=models.TextField(null=True),
        ),
    ]
